service: mppd-api 


plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: "daniel-ribeiro"
  region: sa-east-1
  memorySize: 512
  timeout: 28
  tracing:
    lambda: true
    apiGateway: true
  environment:
    SECRET: ${env:SECRET}
    DATABASE_URL: ${env:DATABASE_URL_PROD}
    SALT_ROUNDS: ${env:SALT_ROUNDS}
    MY_AWS_ACCESS_KEY_ID:  ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY:  ${env:MY_AWS_SECRET_ACCESS_KEY}
  
functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /{any+}
          cors: 
            origins: '*'

package:
  excludeDevDependencies: true
  patterns:
    - '!**/**'
    - 'dist/**'
    - 'node_modules/**'
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
